# Generated by Django 4.2.1 on 2023-06-05 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(default=uuid.uuid4, max_length=200, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("pseudonym", models.CharField(blank=True, max_length=200)),
                ("description", models.CharField(blank=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("lat", models.FloatField(null=True)),
                ("lon", models.FloatField(null=True)),
                ("sensor_config", models.JSONField(blank=True, null=True)),
                ("parser_module", models.CharField(blank=True, max_length=200)),
                ("additional_data_json", models.JSONField(blank=True, null=True)),
                ("unit_of_measurement", models.CharField(blank=True, max_length=200)),
                ("measurement_resolution", models.FloatField(blank=True, null=True)),
                (
                    "quality_indicator",
                    models.CharField(
                        choices=[
                            ("UR", "Unreliable"),
                            ("RE", "Reliable"),
                            ("NP", "Needs Processing"),
                        ],
                        default="RE",
                    ),
                ),
                (
                    "equipment_condition",
                    models.CharField(
                        choices=[
                            ("IN", "Inactive"),
                            ("AC", "Active"),
                            ("NM", "Needs Maintenance"),
                        ],
                        default="AC",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, upload_to="documents/%Y-%m-%d_%H"),
                ),
                ("description", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("area_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="StreamProcessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("DQ", "Data Quality Management"),
                            ("PR", "Parsing"),
                            ("AL", "Alarms"),
                        ],
                        default="PR",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_text", models.TextField(blank=True)),
                (
                    "log_file",
                    models.FileField(blank=True, upload_to="logs/%Y-%m-%d_%H"),
                ),
                ("description", models.CharField()),
                (
                    "type",
                    models.CharField(
                        choices=[("AU", "machine-generated"), ("MA", "manual")],
                        default="MA",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_log_set",
                        to="devices.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstallationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="installation_pics/%Y-%m-%d_%H"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installation_image_set",
                        to="devices.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("additional_data_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True, related_name="docs", to="devices.document"
                    ),
                ),
                (
                    "processors",
                    models.ManyToManyField(
                        blank=True, related_name="modules", to="devices.streamprocessor"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="current_location",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="devices.location",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_set",
                to="devices.devicetype",
            ),
        ),
    ]
