apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mittaridatapumppu.fullname" . }}-configmap
data:
  ALLOWED_IP_ADDRESSES: "{{ .Values.endpoint.allowedIpAddresses }}"
  ENDPOINT_CONFIG_URL: "{{ .Values.endpoint.endpointConfigUrl }}"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.kafka.kafkaBootstrapServers }}"
  KAFKA_GROUP_ID: "{{ .Values.kafka.kafkaGroupId }}"
  KAFKA_PARSED_DATA_TOPIC_NAME: "{{ .Values.kafka.kafkaParsedDataTopicName }}"
  KAFKA_RAW_DATA_TOPIC_NAME: "{{ .Values.kafka.kafkaRawDataTopicName }}"
  DEVICE_REGISTRY_URL: "{{ .Values.parser.deviceRegistryUrl }}"
  DEVICE_REGISTRY_TOKEN: "{{ .Values.parser.deviceRegistryToken }}"
  DJANGO_SETTINGS_MODULE: "{{ .Values.deviceregistry.djangoSettingsModule }}"
  DJANGO_DB_HOST: "{{ .Release.Name }}-{{ .Values.deviceregistry.databaseHost }}"
  DJANGO_DB_USER: "{{ .Values.deviceregistry.databaseUser }}"
  DJANGO_DB_PASSWORD: "{{ .Values.deviceregistry.databasePassword }}"
  DJANGO_DB_PORT: "{{ .Values.deviceregistry.databasePort }}"
  DJANGO_DB_NAME: "{{ .Values.deviceregistry.databaseName }}"
  ALLOWED_HOSTS: "{{ .Values.deviceregistry.allowedHosts | toStrings }}"
  SECRET_KEY: "{{ .Values.deviceregistry.secretKey }}"
  INFLUX_BUCKET: "{{ .Values.persister.influxBucket }}"
  INFLUX_HOST: "{{ .Values.persister.influxHost }}"
  INFLUX_ORG: "{{ .Values.persister.influxOrg }}"
  INFLUX_TOKEN: "{{ .Values.persister.influxToken }}"
  DEBUG: 1
  UVICORN_LOG_LEVEL: "debug"
